[2022-08-05 05:41:42,764] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_first_dag.task_three scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 05:41:42,775] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_first_dag.task_three scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 05:41:42,775] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 05:41:42,776] {taskinstance.py:1377} INFO - Starting attempt 1 of 3
[2022-08-05 05:41:42,776] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 05:41:42,788] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_three> on 2022-08-04 00:00:00+00:00
[2022-08-05 05:41:42,791] {standard_task_runner.py:52} INFO - Started process 249 to run task
[2022-08-05 05:41:42,794] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'task_three', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpzsyjxiuc', '--error-file', '/tmp/tmp_5d0tywo']
[2022-08-05 05:41:42,795] {standard_task_runner.py:80} INFO - Job 41: Subtask task_three
[2022-08-05 05:41:42,851] {task_command.py:371} INFO - Running <TaskInstance: my_first_dag.task_three scheduled__2022-08-04T00:00:00+00:00 [running]> on host 31de0ba96b93
[2022-08-05 05:41:42,913] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=task_three
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-04T00:00:00+00:00
[2022-08-05 05:41:42,914] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-05 05:41:42,915] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo I am partner of task_first']
[2022-08-05 05:41:42,921] {subprocess.py:85} INFO - Output:
[2022-08-05 05:41:42,922] {subprocess.py:92} INFO - I am partner of task_first
[2022-08-05 05:41:42,923] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-05 05:41:43,060] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=task_three, execution_date=20220804T000000, start_date=20220805T054142, end_date=20220805T054143
[2022-08-05 05:41:43,086] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-05 05:41:43,111] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
