[2022-08-05 05:41:41,498] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_first_dag.task_second scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 05:41:41,508] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_first_dag.task_second scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 05:41:41,508] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 05:41:41,508] {taskinstance.py:1377} INFO - Starting attempt 1 of 3
[2022-08-05 05:41:41,509] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 05:41:41,522] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task_second> on 2022-08-04 00:00:00+00:00
[2022-08-05 05:41:41,525] {standard_task_runner.py:52} INFO - Started process 227 to run task
[2022-08-05 05:41:41,527] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'task_second', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpc_e9c73h', '--error-file', '/tmp/tmp9ra_s60l']
[2022-08-05 05:41:41,528] {standard_task_runner.py:80} INFO - Job 38: Subtask task_second
[2022-08-05 05:41:41,587] {task_command.py:371} INFO - Running <TaskInstance: my_first_dag.task_second scheduled__2022-08-04T00:00:00+00:00 [running]> on host 31de0ba96b93
[2022-08-05 05:41:41,656] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=task_second
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-04T00:00:00+00:00
[2022-08-05 05:41:41,657] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-05 05:41:41,658] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello People']
[2022-08-05 05:41:41,665] {subprocess.py:85} INFO - Output:
[2022-08-05 05:41:41,667] {subprocess.py:92} INFO - Hello People
[2022-08-05 05:41:41,667] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-05 05:41:41,825] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=task_second, execution_date=20220804T000000, start_date=20220805T054141, end_date=20220805T054141
[2022-08-05 05:41:41,860] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-05 05:41:41,894] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
